"""
2D Emissivity Map Generator for Multi-Line Single Ion Emissions
Description:
    This script generates 2D emissivity maps for specified emission lines of a single ion
    using data from 2D PION simulation silo files. The output includes .h5 data files and
    PNG plots for visual inspection.

Author: Arun Mathew
Date: 21 Nov 2024
"""

# --- Import Required Libraries ---
import os  # File system operations
import time  # For tracking runtime
import warnings  # Suppress specific runtime warnings
import h5py  # For saving data in HDF5 format
import numpy as np  # Numerical array operations
import matplotlib.pyplot as plt  # Plotting
from mpl_toolkits.axes_grid1 import make_axes_locatable  # For attaching colorbars to axes
from matplotlib.ticker import MultipleLocator, ScalarFormatter  # For controlling tick formatting
import astropy.units as unit  # Astropy units for physical quantities

# --- Import Project Modules ---
import NebulaPy.src as nebula  # NebulaPy simulation interface
from NebulaPy.tools import util  # Utility functions
from pypion.ReadData import ReadData  # Silo data reader

# --- Suppress warnings for log10 of zero ---
warnings.filterwarnings("ignore", category=RuntimeWarning, message="divide by zero encountered in log10")

# --- File and Directory Configuration ---
output_dir = '/home/tony/Desktop/multi-ion-bowshock/sim-output/emissiviity_map'
silo_dir = '/home/tony/Desktop/multi-ion-bowshock/sim-output/silo'
filebase = 'Ostar_mhd-nemo_d2n0128l3'

# --- Simulation Time Parameters ---
start_time = 30  # kyr
finish_time = 31  # kyr
out_frequency = None  # Use all available outputs

# --- Ion and Emission Lines of Interest ---
pion_ion = 'He1+'  # Ion species (e.g., He1+ for singly ionized helium)
lines = [303.78, 303.786]  # Emission line wavelengths in Angstroms

print(rf" calculating line emissivity map of {pion_ion} for lines: {lines} Å")

# --- Get List of Silo Files Based on Time Constraints ---
batched_silos = util.batch_silos(
    silo_dir,
    filebase,
    start_time=start_time,
    finish_time=finish_time,
    time_unit='kyr',
    out_frequency=out_frequency
)

# Total number of time instant
N_time_instant = len(batched_silos)

# --- Load Simulation Data ---
pion = nebula.pion(batched_silos, verbose=True)
pion.load_chemistry()  # Load ion and reaction network data
pion.load_geometry(scale='cm')  # Load spatial grid configuration

# --- Extract Geometry Info ---
geometry = pion.geometry_container
coordinate_sys = geometry['coordinate_sys']
N_grid_level = geometry['Nlevel']
mesh_edges_min = geometry['edges_min']
mesh_edges_max = geometry['edges_max']

# --- Metadata for Output Files ---
heading = f"Generated by {util.nebula_version()}"
metadata = {
    "minimum_mesh_edges": mesh_edges_min,
    "maximum_mesh_edges": mesh_edges_max,
    "Nlevels": N_grid_level
}

# --- Prepare Output Path ---
lines_str = [str(line) for line in lines]
electron_tolerance = 1.E-08  # Floor value for electron density
ion_name = pion_ion.replace('+', 'p')
ion_output_dir = os.path.join(output_dir, ion_name)
os.makedirs(ion_output_dir, exist_ok=True)

data_title = f"Bow-Shock emissivity map for the ion {pion_ion}"

# --- Initialize Line Emission Calculator ---
line_emission = nebula.line_emission(pion_ion, verbose=True)

# --- Loop Through Time Steps ---
runtime = 0.0
for step, silo_instant in enumerate(batched_silos):
    silo_instant_start_time = time.time()

    # --- Get Simulation Time ---
    sim_time = pion.get_simulation_time(silo_instant, time_unit='kyr')
    print(f" ---------------------------")
    print(f" Step: {step}/{N_time_instant - 1} | Simulation Time: {sim_time:.6e} kyr")

    # --- Retrieve Physical Parameters ---
    temperature = pion.get_parameter('Temperature', silo_instant)
    ne = pion.get_ne(silo_instant)

    # --- Calculate Emissivity Maps for All Lines ---
    emissivity_map_dict = line_emission.line_emissivity_map_cylindrical(
        lines, temperature, ne, progress_bar=True
    )

    # --- Save Emissivity Maps to HDF5 ---
    h5_filename = f"{filebase}_emiss_{ion_name}_{str(step).zfill(4)}.h5"
    h5_file = os.path.join(ion_output_dir, h5_filename)
    print(f" Saving emissivity map data into {h5_filename}")

    with h5py.File(h5_file, "w") as file:
        file.attrs['head'] = heading
        file.attrs['title'] = data_title

        meta = file.create_group("metadata")
        for key, value in metadata.items():
            if isinstance(value, list) or isinstance(value, np.ndarray):
                meta.create_dataset(key, data=np.array(value))
            else:
                meta.attrs[key] = value

        emissivity_map_group = file.create_group("emissivity_map")
        for key, value in emissivity_map_dict.items():
            emissivity_map_group.create_dataset(str(key), data=np.array(value, dtype=np.float32))

    # --- Generate and Save Emissivity Map Plots ---
    for line in emissivity_map_dict:
        line_name = line.replace(' ', '')
        fig, ax = plt.subplots(figsize=(8, 6))
        ax.text(0.05, 0.9, f'time = {sim_time.value:5.2f} kyr', transform=ax.transAxes, fontsize=12, color='white')

        ax.set_xlim(mesh_edges_min[0][0].value, mesh_edges_max[0][0].value)
        ax.set_ylim(mesh_edges_min[0][1].value, mesh_edges_max[0][1].value)

        for level in range(N_grid_level):
            plot_data = np.log10(emissivity_map_dict[line][level])
            extents = [
                mesh_edges_min[level][0].value, mesh_edges_max[level][0].value,
                mesh_edges_min[level][1].value, mesh_edges_max[level][1].value
            ]
            image = ax.imshow(plot_data, interpolation='nearest', cmap='inferno',
                              extent=extents, origin='lower', vmin=-25, vmax=-21)

        divider = make_axes_locatable(ax)
        cax = divider.append_axes("right", size="5%", pad=0.05)
        colorbar = plt.colorbar(image, cax=cax, ticks=MultipleLocator(1))
        colorbar.ax.yaxis.set_major_formatter(ScalarFormatter())
        colorbar.ax.yaxis.get_major_formatter().set_scientific(False)
        colorbar.ax.yaxis.get_major_formatter().set_useOffset(False)

        ax.set_xlabel('z (pc)', fontsize=12)
        ax.set_ylabel('R (pc)', fontsize=12)
        ax.text(0.65, 0.9, line, transform=ax.transAxes, fontsize=12, color='white')
        ax.tick_params(axis='both', which='major', labelsize=13)

        filename = f"{filebase}_emiss_{line_name}_{sim_time.value:.2f}kyr.png"
        filepath = os.path.join(ion_output_dir, filename)
        plt.savefig(filepath, bbox_inches="tight", dpi=300)
        plt.close(fig)

        print(f" saving {line:>14} emissivity map to {filename}")

    # --- Track Runtime ---
    dt = time.time() - silo_instant_start_time
    runtime += dt
    print(f" Runtime: {runtime:.4e} s | Δt: {dt:.4e} s")
